/**
 * Created by nghia on 2/13/17.
 */

const TOGGLE_LEADERBOARD = 'TOGGLE_LEADERBOARD';
const RECEIVE_PLAYER = 'RECEIVE_PLAYER';
//expand mode
const TOGGLE_EXPAND_MODE = 'TOGGLE_EXPAND_MODE';
const SET_EXPAND_MODE = 'SET_EXPAND_MODE';
//RESIZE
const CHECK_RESIZE = 'CHECK_RESIZE';
const SET_PLAYER_HEIGHT = 'SET_PLAYER_HEIGHT';

//search
const SEARCH_REQUEST = 'SEARCH_REQUEST';
const SEARCH_FINISH = 'SEARCH_FINISH';
const FETCH_SEARCH_DATA = 'FETCH_SEARCH_DATA';
const CLEAR_SEARCH_DATA = 'CLEAR_SEARCH_DATA';
const SET_KEYWORD = 'SET_KEYWORD';
const SET_DATA = 'SET_DATA';
const SET_SEARCHING = 'SET_SEARCHING';


export {
  TOGGLE_LEADERBOARD,
  RECEIVE_PLAYER,
  TOGGLE_EXPAND_MODE,
  SET_EXPAND_MODE,
  CHECK_RESIZE,
  SET_PLAYER_HEIGHT,
  SEARCH_REQUEST,
  SEARCH_FINISH,
  FETCH_SEARCH_DATA,
  CLEAR_SEARCH_DATA,
  SET_KEYWORD,
  SET_DATA,
  SET_SEARCHING
}